title: OCI Native - Base Infra
description: Basic infrastructure and network rules to start with a Cloud Native project
informationalText: Basic infrastructure
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:

  - title: "Hidden"
    visible: false
    variables:
      - tenancy_ocid
      - compartment_ocid
      - region
      - bastion_subnet_private

  - title: "Network"
    variables:
      - network_compartment_id
      - create_vcn
      - vcn_id
      - vcn_name
      - vcn_cidr_blocks
      - vcn_dns_label
      - cni_type
      - create_cp_subnet
      - cp_subnet_name
      - cp_subnet_cidr
      - cp_subnet_dns_label
      - cp_subnet_private
      - create_cp_public_allow_rule
      - create_worker_subnet
      - worker_subnet_name
      - worker_subnet_cidr
      - worker_subnet_dns_label
      - create_pod_subnet
      - pod_subnet_name
      - pod_subnet_cidr
      - pod_subnet_dns_label
      - create_service_subnet
      - service_subnet_name
      - service_subnet_cidr
      - service_subnet_dns_label
      - service_subnet_private
      - create_fss
      - fss_subnet_name
      - fss_subnet_cidr
      - fss_subnet_dns_label
      - create_gateways
      - nat_gateway_id
      - service_gateway_id
      - create_internet_gateway

  - title: "Bastion"
    variables:
      - create_bastion
      - bastion_subnet_name
      - bastion_subnet_cidr
      - bastion_subnet_dns_label
      - bastion_compartment_id
      - bastion_cidr_block_allow_list

  - title: "Load Balancer"
    visible: ${create_service_subnet}
    variables:
      - create_lb
      - lb_name
      - lb_min_bandwidth
      - lb_max_bandwidth
      - create_lb_http_redirect_rule
      - create_waa

  - title: "API Gateway"
    visible: ${create_service_subnet}
    variables:
      - create_apigw
      - apigw_name

  - title: "DNS"
    variables:
      - create_private_dns_view
      - custom_private_view_name
      - vcn_custom_private_zone_domain_names

  - title: "Vault"
    variables:
      - create_vault
      - vault_compartment_id
      - vault_name

  - title: "Certificate"
    visible: ${create_vault}
    variables:
      - create_certificates
      - certificate_compartment_id
      - root_ca_subject_common_name
      - np_ca_subject_common_name
      - cluster_ca_subject_common_name
      - lb_certificate_subject_common_name
      - apigw_certificate_subject_common_name
      - oke_lb_certificate_name
      - apigw_certificate_name

variables:

  region:
    title: "Region"
    type: oci:identity:region:name
    required: true

  network_compartment_id:
    title: "Network Compartment"
    description: "All resources in this section will be created within the compartment chosen"
    type: oci:identity:compartment:id
    required: true

  cni_type:
    title: "CNI Type"
    description: "CNI to use for the OKE cluster"
    type: enum
    enum:
      - npn
      - flannel
    required: true

# VCN

  create_vcn:
    title: "Create VCN"
    description: "If flagged, this Terraform module will create a VCN"
    type: boolean

  vcn_id:
    title: "Existing VCN"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: ${network_compartment_id}
    required: true
    visible:
      not:
        - ${create_vcn}

  vcn_name:
    title: "VCN Name"
    description: "Name of the VCN to create"
    type: string
    required: true
    visible: ${create_vcn}

  vcn_cidr_blocks:
    title: "VCN CIDR blocks"
    description: "CIDR blocks to be allocated for the VCN"
    type: array
    items:
      type: string
    required: true
    visible: ${create_vcn}

  vcn_dns_label:
    title: "VCN DNS name"
    description: "This dns label will be present by default whenever a new instance is created in the VCN"
    type: string
    required: true
    visible: ${create_vcn}

# CP SUBNET

  create_cp_subnet:
    title: "Create Control Plane subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Control Plane subnet"
    type: boolean

  cp_subnet_cidr:
    title: "Kubernetes Control Plane Subnet CIDR"
    description: "CIDR block to allocate for Kubernetes Control Plane API Server. As it is just one endpoint, it can be small"
    type: string
    required: true
    visible: ${create_cp_subnet}

  cp_subnet_dns_label:
    title: "Kubernetes Control Plane DNS label"
    description: "DNS label for the Kubernetes Control Plane subnet"
    type: string
    required: true
    visible: ${create_cp_subnet}

  cp_subnet_name:
    title: "Kubernetes Control Plane subnet name"
    description: "Name of the subnet containing the Kubernetes Control Plane API Server"
    type: string
    required: true
    visible: ${create_cp_subnet}

  cp_subnet_private:
    title: "Control Plane subnet is private"
    description: "Flag this if the Control Plane subnet is supposed to be private"
    type: boolean
    visible: ${create_cp_subnet}

  create_cp_public_allow_rule:
    title: "Create public Control Plane allow rule"
    description: "Create a rule to allow all traffic to reach the Control Plane"
    type: boolean
    visible:
      and:
        - ${create_cp_subnet}
        - not:
            - ${cp_subnet_private}


# WORKER SUBNET

  create_worker_subnet:
    title: "Create Worker subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Worker subnet"
    type: boolean

  worker_subnet_cidr:
    title: "Worker subnet CIDR"
    description: "CIDR block for OKE worker nodes and other VM or workload like functions"
    type: string
    required: true
    visible: ${create_worker_subnet}

  worker_subnet_dns_label:
    title: "Worker subnet DNS label"
    description: "DNS label for the Worker subnet"
    type: string
    required: true
    visible: ${create_worker_subnet}

  worker_subnet_name:
    title: "Worker subnet name"
    description: "Name of the Worker subnet"
    type: string
    required: true
    visible: ${create_worker_subnet}

# POD SUBNET

  create_pod_subnet:
    title: "Create Pod subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Pod subnet"
    type: boolean
    visible:
      eq:
        - ${cni_type}
        - npn

  pod_subnet_cidr:
    title: "Pod subnet CIDR"
    description: "CIDR block for OKE pods"
    type: string
    required: true
    visible:
      and:
        - ${create_pod_subnet}
        - eq:
            - ${cni_type}
            - npn

  pod_subnet_dns_label:
    title: "Pod subnet DNS label"
    description: "DNS label for the Pod subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_pod_subnet}
        - eq:
            - ${cni_type}
            - npn

  pod_subnet_name:
    title: "Pod subnet name"
    description: "OKE pods will have an IP address assigned from this subnet"
    type: string
    required: true
    visible:
      and:
        - ${create_pod_subnet}
        - eq:
            - ${cni_type}
            - npn

# SERVICE SUBNET

  create_service_subnet:
    title: "Create Service subnet"
    description: "If flagged, this Terraform module will create the Kubernetes Service subnet"
    type: boolean

  service_subnet_cidr:
    title: "Service subnet CIDR"
    description: "CIDR block for the Service subnet"
    type: string
    required: true
    visible: ${create_service_subnet}

  service_subnet_dns_label:
    title: "Service subnet DNS label"
    description: "DNS label for the Service subnet"
    type: string
    required: true
    visible: ${create_service_subnet}

  service_subnet_name:
    title: "Service subnet name"
    description: "The Service subnet will host all the network appliances necessary to expose services, so Load Balancers and API Gateways"
    type: string
    required: true
    visible: ${create_service_subnet}

  service_subnet_private:
    title: "Service Subnet is private"
    description: "If flagged, the service subnet will be a private one, otherwise it's a public subnet"
    type: boolean
    visible: ${create_service_subnet}

# FSS SUBNET

  create_fss:
    title: "Create FSS subnet"
    description: "Create a subnet for the File System Storage service"
    type: boolean

  fss_subnet_name:
    title: "FSS subnet name"
    description: "Name of the FSS subnet to create"
    required: true
    visible: ${create_fss}

  fss_subnet_cidr:
    title: "FSS subnet CIDR"
    description: "CIDR block for the FSS subnet"
    required: true
    visible: ${create_fss}

  fss_subnet_dns_label:
    title: "FSS subnet DNS label"
    description: "DNS label for the FSS subnet"
    required: true
    visible: ${create_fss}

# VCN GATEWAYS

  create_gateways:
    title: "Create VCN Gateways"
    description: "If not flagged, the stack will reuse the VCN gateways"
    type: boolean
    default: true
    visible:
      not:
        - ${create_vcn}

  service_gateway_id:
    type: oci:core:servicegateway:id
    title: Service Gateway
    dependsOn:
      compartmentId: ${network_compartment_id}
      vcnId: ${vcn_id}
    required: true
    visible:
      and:
        - and:
            - ${create_gateways}
            - true
        - not:
            - ${create_vcn}

  nat_gateway_id:
    type: oci:core:natgateway:id
    title: NAT Gateway
    dependsOn:
      compartmentId: ${network_compartment_id}
      vcnId: ${vcn_id}
    required: true
    visible:
      and:
        - and:
            - ${create_vcn}
            - true
        - not:
            - ${create_gateways}

  create_internet_gateway:
    title: "Create_internet_gateway"
    description: "The stack will try to create an Internet Gateway if a public subnet is present. If not flagged, an Internet Gateway will not be created"
    type: boolean
    visible:
      and:
        - and:
            - ${create_vcn}
            - true
        - not:
            - ${create_gateways}

# BASTION SUBNET + BASTION MODULE

  create_bastion:
    title: "Create Bastion"
    description: "If flagged, the Stack creates the Bastion Subnet + an OCI Bastion instance"
    type: boolean

  bastion_subnet_name:
    title: "Bastion subnet name"
    description: "Name of the subnet for Bastions"
    type: string
    required: true
    visible: ${create_bastion}

  bastion_subnet_cidr:
    title: "Bastion subnet CIDR"
    description: "CIDR block to allocate for the Bastion subnet"
    type: string
    required: true
    visible: ${create_bastion}

  bastion_subnet_dns_label:
    title: "Bastion subnet DNS label"
    description: "DNS label for the Bastion subnet"
    type: string
    required: true
    visible: ${create_bastion}

  bastion_compartment_id:
    title: "Bastion Compartment"
    description: "Compartment where to create the OCI Bastion instance"
    type: oci:identity:compartment:id
    required: true
    visible: ${create_bastion}

  bastion_cidr_block_allow_list:
    title: "Bastion allow list"
    description: "CIDR blocks in this list will be able to connect to the OCI Bastion instance"
    type: array
    items:
      type: string
    required: true
    visible: ${create_bastion}

# LOAD BALANCER

  create_lb:
    title: "Create Load Balancer"
    description: "Create a Load Balancer for OKE"
    type: boolean

  lb_name:
    title: "Load Balancer Name"
    description: "Name of the Load Balancer that will be used by OKE to expose pods"
    type: string
    required: true
    visible: ${create_lb}

  lb_min_bandwidth:
    title: "Load Balancer minimum bandwidth"
    description: "Minimum bandwidth to allocate to the Load Balancer"
    type: integer
    minimum: 10
    required: true
    visible: ${create_lb}

  lb_max_bandwidth:
    title: "Load Balancer maximum bandwidth"
    description: "Maximum bandwidth that the Load Balancer can allocate"
    type: integer
    minimum: 10
    required: true
    visible: ${create_lb}

  create_lb_http_redirect_rule:
    title: "Create HTTP redirect rule"
    description: "If flagged, a rule set will be created on the Load Balancer to redirect all HTTP traffic to HTTPS"
    type: boolean
    visible: ${create_lb}

  create_waa:
    title: "Create Web Application Acceleration"
    description: "Create a Web Application Acceleration Policy and attach it to the Load Balancer"
    type: boolean
    visible: ${create_lb}

# APIGW

  create_apigw:
    title: "Create API Gateway"
    description: "Create an API Gateway. Configure it later so that it points to the OKE Load Balancer as backend"
    type: boolean

  apigw_name:
    title: "API Gateway Name"
    description: "Name of the API Gateway"
    type: string
    required: true
    visible: ${create_apigw}

# DNS

  create_private_dns_view:
    title: "Create Private DNS"
    type: boolean

  custom_private_view_name:
    title: "Custom DNS Name - Private View"
    description: "Name of the Private View for the custom DNS names"
    type: string
    required: true
    visible: ${create_private_dns_view}

  vcn_custom_private_zone_domain_names:
    title: "Custom Private Zone Domain Names"
    description: "List of private zones (custom DNS suffixes) to insert in the private view"
    type: array
    items:
      type: string
    required: true
    visible: ${create_private_dns_view}

# VAULT

  create_vault:
    title: "Create Vault"
    description: "Create a sample Vault"
    type: boolean

  vault_compartment_id:
    title: "Vault Compartment"
    description: "Compartment where to create the OCI Vault"
    type: oci:identity:compartment:id
    required: true
    visible: ${create_vault}

  vault_name:
    title: "Vault Name"
    description: "Name of the Vault to create"
    type: string
    required: true
    visible: ${create_vault}

# CERTIFICATE

  create_certificates:
    title: "Create certificates and Certificate Authorities"
    description: "NOTE: Certificates and CAs are very difficult to delete, enable them only if you know what you are doing"
    type: boolean

  certificate_compartment_id:
    title: "Certificate Compartment"
    description: "Compartment where to create the OCI Certificate resources"
    type: oci:identity:compartment:id
    required: true
    visible: ${create_certificates}

  root_ca_subject_common_name:
    title: "Root CA Subject Common Name"
    description: "Subject Common Name for the Root certificate authority"
    type: string
    required: true
    visible: ${create_certificates}

  np_ca_subject_common_name:
    title: "Environment Specific CA Subject Common Name"
    description: "Subordinate Certificate Authority for a specific environment"
    type: string
    required: true
    visible: ${create_certificates}

  cluster_ca_subject_common_name:
    title: "Cluster CA Subject Common Name"
    description: "Subordinate Certificate Authority for the OKE cluster"
    type: string
    required: true
    visible: ${create_certificates}

  lb_certificate_subject_common_name:
    title: "Load Balancer certificate Subject Common Name"
    description: "Subject Common Name of the OKE Load Balancer certificate"
    type: string
    required: true
    visible:
      and:
        - ${create_certificates}
        - ${create_lb}

  apigw_certificate_subject_common_name:
    title: "API Gateway certificate Subject Common Name"
    description: "Subject Common Name of the API Gateway certificate"
    type: string
    required: true
    visible:
      and:
        - ${create_certificates}
        - ${create_apigw}

  oke_lb_certificate_name:
    title: "OKE Load Balancer certificate name"
    description: "Certificate name for the OKE Load Balancer"
    type: string
    required: true
    visible:
      and:
        - ${create_certificates}
        - ${create_lb}

  apigw_certificate_name:
    title: "API Gateway certificate name"
    description: "Certificate name for the API Gateway"
    type: string
    required: true
    visible:
      and:
        - ${create_certificates}
        - ${create_apigw}
